apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-tech-platform
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/rishgoyal/gitops-tech-platform
  ref:
    branch: main
  secretRef:
    name: github-auth-https