apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: gitops-tech-platform
  namespace: flux-system
spec:
  interval: 1m
  destroy: true
  approvePlan: auto
  path: ./terraform
  sourceRef:
    kind: GitRepository
    name: gitops-tech-platform
    namespace: flux-system
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: azure-tf-creds
      # env:
      # - name: ARM_CLIENT_ID
      #   valueFrom:
      #     secretKeyRef:
      #       name: azure-tf-creds
      #       key: ARM_CLIENT_ID
      # - name: ARM_CLIENT_SECRET
      #   valueFrom:
      #     secretKeyRef:
      #       name: azure-tf-creds
      #       key: ARM_CLIENT_SECRET
      # - name: ARM_SUBSCRIPTION_ID
      #   valueFrom:
      #     secretKeyRef:
      #       name: azure-tf-creds
      #       key: ARM_SUBSCRIPTION_ID 
      # - name: ARM_TENANT_ID
      #   valueFrom:
      #     secretKeyRef:
      #       name: azure-tf-creds
      #       key: ARM_TENANT_ID
      